### PR TITLE
review the changes 

### PR DESCRIPTION
**Pull request by Manikanta528**
@debanjana-a11y review it 

1. Adjusted hambugerMenu
2. removed background of the image
3. changed the darkmode switch to the bottom

### CODE REVIEW

**Comment by debanjana-a11y** [comment]
The output looks cool. I think the "Dark" word in button is not needed anymore, since it does not change with mode and the switch's purpose is pretty obvious without it. Either we can change the word with mode switch or simply remove.

just noticed this, some extra buttons which does not wor, do you see the same in your setup ? 

image

**Comment by Manikanta528** [comment]
yeah it was 
i was not able get those root color's to change 

just changed some adjustments.
could you help on those root color's

**Comment by debanjana-a11y** [comment]
> yeah it was i was not able get those root color's to change
> 
> just changed some adjustments. could you help on those root color's

yeah sure, first of all we dont need those small buttons in dialog, let me check code and get back to you soon.

**Comment by debanjana-a11y** [comment]
@Manikanta528, I made progress with your changes, giving you the patch file of mine, please follow these steps with this patch
[dark_Mode_changes.txt](https://github.com/debanjana-a11y/TodoList/files/9794180/dark_Mode_changes.txt)

Steps:
Revert your local changes and start from main -> download "dark_Mode_changes.txt" -> put it in your TodoList Folder -> then apply "git apply <patch file name>"
example command:  C:\Users\GitHub\TodoList> git apply dark_Mode_changes.txt

With my changes it should look like following. Can you take it further and complete the rest ? Please let me know if you have query or need help.

image

**Comment by debanjana-a11y** [comment]
@Manikanta528 Is there any update for this ? Were you able to successfully apply the patch file in your code ?

Maybe you should try this patch instead of the previous. 
[Dark_Mode_changes.txt](https://github.com/debanjana-a11y/TodoList/files/9832253/Dark_Mode_changes.txt)

**Comment by Manikanta528** [comment]
@debanjana-a11y patch file didn't work on my machine

**Comment by debanjana-a11y** [comment]
> @debanjana-a11y patch file didn't work on my machine

You have to go back old 

> @debanjana-a11y patch file didn't work on my machine

I missed this warning, maybe it caused the failure in your setup. 
warning: LF will be replaced by CRLF in dist/main.js.
The file will have its original line endings in your working directory

I committed the changes in new branch "branch_ISSUE_4". Would suggest you to continue from this branch.

**Comment by debanjana-a11y** [comment]
> @debanjana-a11y patch file didn't work on my machine

 I missed this warning, maybe it caused the failure in your setup. 
"warning: LF will be replaced by CRLF in dist/main.js. The file will have its original line endings in your working directory"

I committed the changes in new branch "branch_ISSUE_4". Would suggest you to continue from this branch.

**Comment by Manikanta528** [comment]
@debanjana-a11y  
branch_issue_4 looks great 
merge the  branch
and close the issue.

**Comment by debanjana-a11y** [comment]
> @debanjana-a11y branch_issue_4 looks great merge the branch and close the issue.

Sure, thanks for your contributions and all these discussions. It was nice to collab with you.

Will make another pull request to merge, hence closing this one.

**Pull request closed without merging**
