### PR TITLE
Added Dark Mode #4

### PR DESCRIPTION
**Pull request by Manikanta528**

### CODE REVIEW

**Comment by debanjana-a11y** [comment]
Hi @Manikanta528 ,

I tried with the fix, I loved the mode change button design and how it is working. However there are few points, 
1. The responsiveness seems broken, e.g please try with width = 381 and height = 658.
2. The Task names are unreadable in dark mode. Also this "no work pending for today" image looks off. We can use different image or maybe remove the background of this existing image and use that in dark mode. There are tools like this 
https://www.remove.bg/upload

image

3. I was thinking should we do more color change in dark mode ? Like these were my preliminary designs when I started, 

image

Do you have better idea on the looks ?

4. Also I am in confusion where the mode change button looks best in page., like beside the Logo or above the "Add new Project" or attached as fixed as shown in picture or anywhere better ? 

Please feel free to share your opinions :)

**Comment by Manikanta528** [comment]
design looks great

**Comment by debanjana-a11y** [comment]
> design looks great

Alright, then we can make css colors and the mode change button more or less like that design. You are working on it right ? Feel free to change this if you like to.

**Comment by Manikanta528** [comment]
i been working on it but those css root color's are not changing while on dark mode

**Comment by debanjana-a11y** [comment]
Alright, it seems that few new class selectors need to be introduced in dark mode theme. This is a good starting point for us, I will change the css colors later to make them work perfctly with your codes. Thanks for the help :)).

**Pull request merged**
